import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

class DownpeedIcons {
  const DownpeedIcons._();

  static const IconData overview = LucideIcons.layoutDashboard300;
  static const IconData all = LucideIcons.inbox300;
  static const IconData active = LucideIcons.arrowDownToLine300;
  static const IconData completed = LucideIcons.circleCheck300;
  static const IconData issues = LucideIcons.circleAlert300;
  static const IconData settings = LucideIcons.settings300;
  static const IconData sidebarClose = LucideIcons.panelLeftClose300;
  static const IconData sidebarOpen = LucideIcons.panelLeftOpen300;
  static const IconData systemTheme = LucideIcons.monitor300;
  static const IconData lightTheme = LucideIcons.sun300;
  static const IconData darkTheme = LucideIcons.moon300;
  static const IconData language = LucideIcons.languages300;
  static const IconData layout = LucideIcons.panelLeft300;
  static const IconData tools = LucideIcons.slidersHorizontal300;
  static const IconData add = LucideIcons.plus300;
  static const IconData minus = LucideIcons.minus300;
  static const IconData paste = LucideIcons.clipboardPaste300;
  static const IconData retry = LucideIcons.rotateCcw300;
  static const IconData search = LucideIcons.search300;
  static const IconData sort = LucideIcons.arrowDownUp300;
  static const IconData engine = LucideIcons.gauge300;
  static const IconData scheduler = LucideIcons.workflow300;
  static const IconData speedLimit = LucideIcons.gauge300;
  static const IconData retryPolicy = LucideIcons.listRestart300;
  static const IconData download = LucideIcons.download300;
  static const IconData magnet = LucideIcons.magnet300;
  static const IconData torrentFile = LucideIcons.fileUp300;
  static const IconData back = LucideIcons.arrowLeft300;
  static const IconData link = LucideIcons.link300;
  static const IconData file = LucideIcons.file300;
  static const IconData server = LucideIcons.server300;
  static const IconData connections = LucideIcons.network300;
  static const IconData shield = LucideIcons.shieldCheck300;
  static const IconData locked = LucideIcons.lockKeyhole300;
  static const IconData upload = LucideIcons.upload300;
  static const IconData database = LucideIcons.database300;
  static const IconData diagnostics = LucideIcons.activity300;
  static const IconData archive = LucideIcons.fileArchive300;
  static const IconData storage = LucideIcons.hardDrive300;
  static const IconData logs = LucideIcons.scrollText300;
  static const IconData info = LucideIcons.info300;
  static const IconData close = LucideIcons.x300;
  static const IconData folder = LucideIcons.folderOpen300;
  static const IconData openFile = LucideIcons.file300;
  static const IconData revealFile = LucideIcons.folderOpen300;
  static const IconData stop = LucideIcons.circleStop300;
  static const IconData pause = LucideIcons.pause300;
  static const IconData resume = LucideIcons.play300;
  static const IconData delete = LucideIcons.trash2300;
  static const IconData clock = LucideIcons.clock3300;
  static const IconData more = LucideIcons.chevronRight300;
  static const IconData expand = LucideIcons.chevronDown300;
  static const IconData path = LucideIcons.folderTree300;
  static const IconData notifications = LucideIcons.bell300;
  static const IconData keyboard = LucideIcons.keyboard300;
  static const IconData tray = LucideIcons.panelTop300;
  static const IconData startup = LucideIcons.logIn300;
  static const IconData about = LucideIcons.badgeInfo300;
  static const IconData licenses = LucideIcons.scrollText300;
}
